dist: bionic
language: node_js
node_js:
  - '10'
  - '12'
  - node

addons:
  apt:
    packages:
      - asciidoctor
      - pandoc

cache:
  yarn: true
  npm: false

install:
  - yarn install

script:
  - yarn build
  - yarn test
  - yarn lint
  - yarn readme2md

deploy:
  provider: npm
  email: jakub@jirutka.cz
  api_key:
    secure: TODO
  skip_cleanup: true
  on:
    tags: true
    node_js: '10'
